// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZZ0kXG-J8_yqOxILX7f5RGku3hKosGE',
    appId: '1:1006910022988:web:bd20eeb49d060da72a5be9',
    messagingSenderId: '1006910022988',
    projectId: 'swap-skill-8e1a1',
    authDomain: 'swap-skill-8e1a1.firebaseapp.com',
    storageBucket: 'swap-skill-8e1a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIVjqcdx7qVLTadXwOB6kqgcwbux3qmAI',
    appId: '1:1006910022988:android:200e6f8806bf4f152a5be9',
    messagingSenderId: '1006910022988',
    projectId: 'swap-skill-8e1a1',
    storageBucket: 'swap-skill-8e1a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNYXXQd0RaJdhduwg2e4szyvgixy6CvDo',
    appId: '1:1006910022988:ios:f4e215447ecbd4d62a5be9',
    messagingSenderId: '1006910022988',
    projectId: 'swap-skill-8e1a1',
    storageBucket: 'swap-skill-8e1a1.firebasestorage.app',
    iosBundleId: 'com.example.swapSkill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNYXXQd0RaJdhduwg2e4szyvgixy6CvDo',
    appId: '1:1006910022988:ios:f4e215447ecbd4d62a5be9',
    messagingSenderId: '1006910022988',
    projectId: 'swap-skill-8e1a1',
    storageBucket: 'swap-skill-8e1a1.firebasestorage.app',
    iosBundleId: 'com.example.swapSkill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiZZ0kXG-J8_yqOxILX7f5RGku3hKosGE',
    appId: '1:1006910022988:web:117e9623199df5132a5be9',
    messagingSenderId: '1006910022988',
    projectId: 'swap-skill-8e1a1',
    authDomain: 'swap-skill-8e1a1.firebaseapp.com',
    storageBucket: 'swap-skill-8e1a1.firebasestorage.app',
  );
}
